#Change these directories for each sample
read_1_file: "/home/caleb/scDNA_analysis/Sequencing_data/IFD21/IFD21_S163_L006_R1_001.fastq.gz"
read_2_file: "/home/caleb/scDNA_analysis/Sequencing_data/IFD21/IFD21_S163_L006_R2_001.fastq.gz"
fastq_out_folder: "/home/caleb/scDNA_analysis/Sequencing_data/IFD21/fastq_out/"

#Only change these once you clone the Git on your local computer
demuxbyname_path: "/home/caleb/scDNA_analysis/bbmap/demuxbyname.sh"
barcode_whitelist_1: "/home/caleb/scDNA_analysis/IF_Analysis/MB_whitelist/bc1_whitelist_num.json"
barcode_whitelist_2: "/home/caleb/scDNA_analysis/IF_Analysis/MB_whitelist/bc2_whitelist_num.json"
primer_csv: "/home/caleb/scDNA_analysis/AML-v2RevA-design-summary.csv"
bwamem2: "/home/caleb/scDNA_analysis/Reference2/Ref_Genome"
human_fastq_file: "/home/caleb/scDNA_analysis/genome.fa"
interval_file: "/home/caleb/scDNA_analysis/AML-v2RevA-GRCh38_GM1_GM2.bed"
bwamem2_path: "/home/caleb/scDNA_analysis/bwa-mem2-2.2.1_x64-linux/bwa-mem2"
samtools_path: "/programs/bin/samtools"
gatk_path: "/home/caleb/scDNA_analysis/gatk-4.1.3.0/gatk"
truth_GM1_GM2_variant: "/home/caleb/scDNA_analysis/GrCh38_GM1_GM2_variants/GM1_GM2_variant_list.csv"

