#Change these directories for each sample
read_1_file: "/path/to/read/1" #Should be in fastq.gz (unzipped format)
read_2_file: "/path/to/read/2" #Should be in fastq.gz (unzipped format)
fastq_out_folder: "/path/to/folder/where/you/want/to/store/result" 

#Only change these once you clone the Git on your local computer
demuxbyname_path: "/path/to/bbmap/demuxbyname.sh" #Download from https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/bbmap-guide/ and locate in your local setup
bwamem2_path: "/path/to/bwa-mem2" #Download from https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.2.1/bwa-mem2-2.2.1_x64-linux.tar.bz2 and locate in your local setup
samtools_path: "/path/to/samtools" #Download from https://www.htslib.org/ and locate in your local setup
gatk_path: "/path/to/gatk" #Download GATK 4.1.3.0 from https://gatk.broadinstitute.org/hc/en-us/sections/360007279472-4-1-3-0 and locate in your local setup

barcode_whitelist_1: "/path/to/bc1_whitelist_num.json" #Should be in ./barcode_whitelist
barcode_whitelist_2: "/path/to/bc2_whitelist_num.json" #Should be in ./barcode_whitelist
primer_csv: "/path/to/AML-v2RevA-design-summary.csv" #Should be in ./primer_set
interval_file: "/path/toAML-v2RevA-GRCh38_GM1_GM2.bed" #Should be in ./primer_set
truth_GM1_GM2_variant: "path/to/GM1_GM2_variant_list.csv" #Should be in ./truth_variant

bwamem2: "/path/to/Ref_Genome/folder" #Download from Dropbox link and locate in your local setup
human_fastq_file: "/path/to/genome.fa" #Download from Dropbox link and locate in your local setup




